character_collector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home_1'),
    path('about/', views.about, name='about'),
    path('characters/', views.characters_index, name='index'),
    path('characters/<int:character_id>/', views.character_detail, name='detail'),
    path('characters/create/', views.CharacterCreate.as_view(), name='characters_create'),
    path('characters/<int:pk>/update/', views.CharacterUpdate.as_view(), name= 'characters_update'),
    path('characters/<int:pk>/delete/', views.CharacterDelete.as_view(), name= 'characters_delete'),

    path('items/', views.items_index, name='items_index'),
    path('items/<int:item_id>/', views.item_detail, name='itemdetail'),
    path('items/create/', views.ItemCreate.as_view(), name='items_create'),
    path('items/<int:pk>/update/', views.ItemUpdate.as_view(), name= 'items_update'),
    path('items/<int:pk>/delete/', views.ItemDelete.as_view(), name= 'items_delete'),
    path('characters/<int:character_id>/add_session/', views.add_session, name= 'add_session'),
    path('characters/<int:character_id>/assoc_item/<int:item_id>/', views.assoc_item, name='assoc_item'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class Item(models.Model):
    name = models.CharField(max_length=100)
    notes = models.TextField(max_length=250)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("itemdetail", kwargs={"item_id": self.id})

class Character(models.Model):
    name = models.CharField(max_length=100)
    race = models.CharField(max_length=100)
    background = models.CharField(max_length=100)
    level = models.IntegerField()
    style = models.CharField(max_length=100)

    items = models.ManyToManyField(Item)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("detail", kwargs={"character_id": self.id})
    

class Session(models.Model):
    date = models.DateField('Session Date')
    session = models.TextField(max_length=250)

    character = models.ForeignKey(Character, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.session} on {self.date}"
    
    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Session

class SessionForm(ModelForm):
  class Meta:
    model = Session
    fields = ['date', 'session']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Character, Item
from .forms import SessionForm
# Create your views here.


class CharacterCreate(CreateView):
    model = Character
    fields = ['name', 'race', 'background', 'level', 'style']
    success_url = '/characters/'

class CharacterUpdate(UpdateView):
    model = Character
    fields = ['name', 'race', 'background', 'level', 'style']

class CharacterDelete(DeleteView):
    model = Character
    success_url = '/characters/'

class ItemCreate(CreateView):
    model = Item
    fields = ['name', 'notes']
    success_url = '/items/'

class ItemUpdate(UpdateView):
    model = Item
    fields = ['name', 'notes']

class ItemDelete(DeleteView):
    model = Item
    success_url = '/items/'


def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def characters_index(request):
    characters = Character.objects.all()
    return render(request, 'characters/index.html', {'characters': characters})

def character_detail(request, character_id):
    character = Character.objects.get(id=character_id)
    id_list = character.items.all().values_list('id')
    items_character_doesnt_have = Item.objects.exclude(id__in=id_list)
    session_form = SessionForm()
    return render(request, 'characters/detail.html', {
        'character' : character, 'session_form': session_form,
        'items': items_character_doesnt_have
    })


def items_index(request):
    items = Item.objects.all()
    return render(request, 'items/items_index.html', {'items': items})

def item_detail(request, item_id):
    item = Item.objects.get(id=item_id)
    return render(request, 'items/items_detail.html', { 'item': item })

def add_session(request, character_id):
  # create a ModelForm instance using the data in request.POST
  form = SessionForm(request.POST)
  # validate the form
  if form.is_valid():
    # don't save the form to the db until it
    # has the cat_id assigned
    new_session = form.save(commit=False)
    new_session.character_id = character_id
    new_session.save()
  return redirect('detail', character_id=character_id)

def assoc_item(request, character_id, item_id):
    Character.objects.get(id=character_id).items.add(item_id)
    return redirect('detail', character_id=character_id)

# class Character:
#     def __init__(self, name, race, background, level, style):
#         self.name = name
#         self.race = race
#         self.background = background
#         self.level = level
#         self.style = style

# characters = [
#     Character('Dragur Fallrag', 'Dwarf', 'Fisherman', 7, 'Bard'),
#     Character('Huddol Wintervine', 'Elf', 'Smuggler', 3, 'Rogue'),
#     Character('Kindi Eveningfall', 'Human', 'Sage', 15 , 'Druid'),
#     Character('Trax Idlehands', 'Dragonborn', 'Soldier', 8, 'Fighter')
# ]

main_app/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Character Collector</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block content %}
    <h1>About the Character Collector</h1>
<hr />
<p>Collect the characters you've created for different campaigns!!</p>
    {%endblock %}
<footer>All Rights Reserved, &copy; 2022 Character Collector</footer>

  
</body>
</html>

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Character Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;CharacterCollector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'home_1' %}">Home</a></li>
          <li><a href="{% url 'index' %}">Characters</a></li>
          <li><a href="{% url 'characters_create' %}">Create a Character</a></li>
          <li><a href="{% url 'items_index' %}">Items</a></li>
          <li><a href="{% url 'items_create' %}">Create an Item</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2022 Character Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/characters/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Character Details</h1>
<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ character.name }}</span>
                <p>Race: {{ character.race }}</p>
                <p>Background: {{ character.background }}</p>
                <p>Level: {{ character.level }}</p>
                <p>Class: {{ character.style }}</p>
            </div>
    <div class= "card-action">
        <a href= "{% url 'characters_update' character.id%}">Edit Character</a>
        <a href= "{% url 'characters_delete' character.id%}">Delete Character</a>
    </div>
</div>
</div>
<div class="col s6">
    <form action="{% url 'add_session' character.id %}" method="POST">
        {% csrf_token %}
        {{ session_form.as_p }}
        <input type="submit" class="btn" value="Add Session">
      </form>
    <table class="striped">
        <thead>
            <tr><th>Date</th><th>Session Notes</th></tr>
          </thead>
          <tbody>
            {% for session in character.session_set.all %}
              <tr>
                <td>{{session.date}}</td>
                <td>{{session.session}}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
  </div>
  <hr>
<div class="row">
  <div class="col s6">
    <h3>{{ character.name }}'s Items</h3>
    {% if character.items.count %}
      {% for item in character.items.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A  {{ item.name }}
            </span>
            <p>{{item.notes}}</p>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Items </h5>
    {% endif %}
  </div>
  <div class="col s6">
    <h3>Available Items</h3>
    {% if items.count %}
      {% for item in items.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A  {{ item.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_item' character.id item.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{character.name}} - Already Has All Items Available</h5>
    {% endif %}
  </div>
</div>

<script>
    const dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
      format: 'yyyy-mm-dd',
      defaultDate: new Date(),
      setDefaultDate: true,
      autoClose: true
    });
</script>
{% endblock %}

main_app/templates/characters/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Character List</h1>

{% for character in characters %}
  <div class="card">
    <a href='{% url 'detail' character.id %}'>
    <div class="card-content">

      <span class="card-title">{{ character.name }}</span>
      <p>Race: {{ character.race }}</p>
      <p>Background: {{ character.background }}</p>
      <p>Level: {{ character.level }}</p>
      <p>Class: {{ character.style }}</p>

    </div>
    </a>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Character Collector</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block content %}
    <h1>Home Page</h1>
<hr />

    {%endblock %}
<footer>All Rights Reserved, &copy; 2022 Character Collector</footer>

  
</body>
</html>

main_app/templates/items/items_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Item Details</h1>

<div class="card">
  <div class="card-content">

    <span class="card-title">{{ item.name }}</span>
    <p>Item Notes: {{ item.notes }}</p>
  
    <div class= "card-action">
        <a href= "{% url 'items_update' item.id%}">Edit Item</a>
        <a href= "{% url 'items_delete' item.id%}">Delete Item</a>
    </div>

  </div>
</div>

{% endblock %}

main_app/templates/items/items_index.html
{% extends 'base.html' %}
{% block content %}

<h1>Item List</h1>

{% for item in items %}
  <div class="card">
    <a href='{% url 'itemdetail' item.id %}'>
    <div class="card-content">

      <span class="card-title">{{ item.name }}</span>
      <p>Item Notes: {{ item.notes }}</p>


    </div>
    </a>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/main_app/character_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Character</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' character.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/character_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
  <h1>You are currently editing <span class= "teal-text">{{object.name}}</span></h1>
{% else %}
    <h1>Create a Character</h1>
{% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/item_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Item</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'itemdetail' item.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/item_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
  <h1>You are currently editing <span class= "teal-text">{{object.name}}</span></h1>
{% else %}
    <h1>Create an Item</h1>
{% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}